import os
import logging
import base64
import json
from PySide6 import QtCore, QtWidgets

AICODEPREP_GUI_VERSION = "1.0"


PREFS_DIR_NAME = ".aicp"
PREFS_FILE_NAME = "preferences.ini"
LEGACY_PREFS_FILES = [".aicodeprep-gui", ".auicp"]


def _prefs_dir():
    return os.path.join(os.getcwd(), PREFS_DIR_NAME)


def _prefs_path():
    """Get the path to the new preferences file."""
    return os.path.join(_prefs_dir(), PREFS_FILE_NAME)


def _legacy_prefs_paths():
    return [os.path.join(os.getcwd(), name) for name in LEGACY_PREFS_FILES]


def _existing_prefs_path():
    """Return the first existing preferences path (new first, then legacy)."""
    new_path = _prefs_path()
    if os.path.exists(new_path):
        return new_path, False
    for path in _legacy_prefs_paths():
        if os.path.exists(path):
            return path, True
    return new_path, False


def _write_prefs_file(
    checked_relpaths,
    window_size=None,
    splitter_state=None,
    output_format=None,
    pro_features=None,
    prefs_path=None,
    dock_state=None,
    dock_widgets_state=None,
):
    """Write preferences to .aicp/preferences.ini or a legacy path."""
    new_path = prefs_path or _prefs_path()
    try:
        parent_dir = os.path.dirname(new_path)
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)
        with open(new_path, "w", encoding="utf-8") as f:
            header = (
                f"# .aicp project preferences file\n"
                f"# This file stores your preferences (checked code files, window size) for this folder.\n"
                f"# Generated by aicodeprep-gui.\n"
                f"# Homepage: https://wuu73.org/aicp\n"
                f"# GitHub: https://github.com/detroittommy879/aicodeprep-gui\n"
                f"# ----------------------------------------------------------\n"
                f"# aicodeprep-gui preferences file version {AICODEPREP_GUI_VERSION}\n"
            )
            f.write(header)
            f.write(f"version={AICODEPREP_GUI_VERSION}\n\n")
            if window_size:
                f.write(
                    f"[window]\nwidth={window_size[0]}\nheight={window_size[1]}\n")
                if splitter_state is not None:
                    splitter_data = base64.b64encode(
                        splitter_state).decode('utf-8')
                    f.write(f"splitter_state={splitter_data}\n")
                if dock_state is not None:
                    dock_data = base64.b64encode(dock_state).decode('utf-8')
                    f.write(f"dock_state={dock_data}\n")
                if dock_widgets_state:
                    widgets_payload = base64.b64encode(
                        json.dumps(dock_widgets_state).encode("utf-8")
                    ).decode("utf-8")
                    f.write(f"dock_widgets_state={widgets_payload}\n")
                f.write("\n")
            if output_format in ("xml", "markdown"):
                f.write(f"[format]\noutput_format={output_format}\n\n")
            if pro_features:
                f.write("[pro]\n")
                for key, value in pro_features.items():
                    f.write(f"{key}={str(value).lower()}\n")
                f.write("\n")
            if checked_relpaths:
                f.write("[files]\n" + "\n".join(checked_relpaths) + "\n")
        logging.info(f"Saved preferences to {new_path}")
    except Exception as e:
        logging.warning(f"Could not write project preferences: {e}")


def _read_prefs_file():
    """Read preferences with backwards compatibility for legacy files.

    Returns checked, window_size, splitter_state, output_format, pro_features,
    prefs_path, prefs_is_legacy.
    """
    checked, window_size, splitter_state = set(), None, None
    dock_state, dock_widgets_state = None, {}
    width_val, height_val = None, None
    output_format = "xml"
    pro_features = {}

    prefs_path, prefs_is_legacy = _existing_prefs_path()

    try:
        with open(prefs_path, "r", encoding="utf-8") as f:
            section = None
            for line in f.read().splitlines():
                if line.strip().startswith('[') and line.strip().endswith(']'):
                    section = line.strip()[1:-1]
                    continue
                if not section:
                    continue

                if section == "files":
                    if line.strip():
                        checked.add(line.strip())
                elif section == "window":
                    if line.startswith('width='):
                        try:
                            width_val = int(line.split('=')[1])
                        except (ValueError, IndexError):
                            pass
                    elif line.startswith('height='):
                        try:
                            height_val = int(line.split('=')[1])
                        except (ValueError, IndexError):
                            pass
                    elif line.startswith('splitter_state='):
                        try:
                            splitter_data = line.split('=', 1)[1]
                            splitter_state = base64.b64decode(
                                splitter_data.encode('utf-8'))
                        except Exception as e:
                            logging.warning(
                                f"Failed to decode splitter state: {e}")
                    elif line.startswith('dock_state='):
                        try:
                            dock_data = line.split('=', 1)[1]
                            dock_state = base64.b64decode(
                                dock_data.encode('utf-8'))
                        except Exception as e:
                            logging.warning(
                                f"Failed to decode dock state: {e}")
                    elif line.startswith('dock_widgets_state='):
                        try:
                            widgets_data = line.split('=', 1)[1]
                            dock_widgets_state = json.loads(
                                base64.b64decode(widgets_data.encode(
                                    'utf-8')).decode('utf-8')
                            )
                        except Exception as e:
                            logging.warning(
                                f"Failed to decode dock widgets state: {e}")
                elif section == "format":
                    if line.startswith("output_format="):
                        val = line.split("=", 1)[1].strip().lower()
                        if val in ("xml", "markdown"):
                            output_format = val
                elif section == "pro":
                    if "=" in line:
                        key, value = line.split("=", 1)
                        key = key.strip()
                        value = value.strip().lower()
                        # Convert string boolean to actual boolean
                        if value in ("true", "false"):
                            pro_features[key] = value == "true"
                        else:
                            pro_features[key] = value

            if width_val is not None and height_val is not None:
                window_size = (width_val, height_val)

    except FileNotFoundError:
        logging.info(
            "Project preferences file not found, will create on save.")
    except Exception as e:
        logging.error(f"Error reading preferences file: {e}")

    return checked, window_size, splitter_state, output_format, pro_features, prefs_path, prefs_is_legacy, dock_state, dock_widgets_state


class PreferencesManager:
    def __init__(self, main_window):
        self.main_window = main_window
        self.checked_files_from_prefs = set()
        self.window_size_from_prefs = None
        self.splitter_state_from_prefs = None
        self.output_format_from_prefs = "xml"
        self.pro_features_from_prefs = {}
        self.dock_state_from_prefs = None
        self.dock_widgets_state_from_prefs = {}
        # True only if a prefs file actually exists on disk
        self.prefs_file_exists = False
        # Backward-compat flag; set true only when prefs file exists
        self.prefs_loaded = False
        # Track the prefs source path for migration prompts
        self.prefs_path = None
        self.prefs_is_legacy = False
        # When legacy prefs are in use, keep writing to legacy until user migrates
        self.write_legacy_prefs = False
        # Track fullcode.txt for migration
        self.has_legacy_fullcode = os.path.exists("fullcode.txt")

    def load_prefs_if_exists(self):
        # Determine if a prefs file exists before reading so we don't override smart defaults when missing
        prefs_path, prefs_is_legacy = _existing_prefs_path()
        self.prefs_file_exists = os.path.exists(prefs_path)
        self.has_legacy_fullcode = os.path.exists("fullcode.txt")

        checked, window_size, splitter_state, output_format, pro_features, prefs_path, prefs_is_legacy, dock_state, dock_widgets_state = _read_prefs_file()
        self.checked_files_from_prefs = checked
        self.window_size_from_prefs = window_size
        self.splitter_state_from_prefs = splitter_state
        self.output_format_from_prefs = output_format
        self.pro_features_from_prefs = pro_features
        self.dock_state_from_prefs = dock_state
        self.dock_widgets_state_from_prefs = dock_widgets_state
        self.prefs_path = prefs_path
        self.prefs_is_legacy = prefs_is_legacy
        self.write_legacy_prefs = prefs_is_legacy and not os.path.exists(
            _prefs_path())

        # Only mark as loaded when a prefs file actually exists
        self.prefs_loaded = self.prefs_file_exists

    def save_prefs(self):
        checked_relpaths = []
        for rel_path, item in self.main_window.path_to_item.items():
            if item.checkState(0) == QtCore.Qt.Checked:
                file_path_abs = item.data(0, QtCore.Qt.UserRole)
                if file_path_abs and os.path.isfile(file_path_abs):
                    checked_relpaths.append(rel_path)
        size = self.main_window.size()
        splitter_state = self.main_window.splitter.saveState()
        fmt = self.main_window.format_combo.currentData()

        # Collect pro features state
        pro_features = {}
        if hasattr(self.main_window, 'preview_toggle'):
            preview_window = getattr(self.main_window, 'preview_window', None)
            pro_features['preview_window_enabled'] = bool(
                preview_window.isVisible()) if preview_window else self.main_window.preview_toggle.isChecked()
        if hasattr(self.main_window, 'syntax_highlight_toggle'):
            pro_features['syntax_highlight_enabled'] = self.main_window.syntax_highlight_toggle.isChecked()
        if hasattr(self.main_window, 'flow_studio_toggle'):
            flow_dock = getattr(self.main_window, 'flow_dock', None)
            pro_features['flow_studio_enabled'] = bool(
                flow_dock.isVisible()) if flow_dock else self.main_window.flow_studio_toggle.isChecked()
        if hasattr(self.main_window, 'ai_chat_toggle'):
            ai_chat_dock = getattr(self.main_window, 'ai_chat_dock', None)
            pro_features['ai_chat_enabled'] = bool(
                ai_chat_dock.isVisible()) if ai_chat_dock else self.main_window.ai_chat_toggle.isChecked()

        dock_state = None
        dock_widgets_state = {}
        try:
            dock_state = bytes(self.main_window.saveState())
        except Exception as e:
            logging.warning(f"Could not capture main dock state: {e}")

        flow_dock = getattr(self.main_window, 'flow_dock', None)
        if flow_dock and hasattr(flow_dock, 'get_layout_state'):
            try:
                dock_widgets_state['flow_studio'] = flow_dock.get_layout_state()
            except Exception as e:
                logging.warning(
                    f"Could not capture Flow Studio layout state: {e}")

        ai_chat_dock = getattr(self.main_window, 'ai_chat_dock', None)
        if ai_chat_dock and hasattr(ai_chat_dock, 'get_layout_state'):
            try:
                dock_widgets_state['ai_chat'] = ai_chat_dock.get_layout_state()
            except Exception as e:
                logging.warning(f"Could not capture AI Chat layout state: {e}")

        _write_prefs_file(
            checked_relpaths,
            window_size=(size.width(), size.height()),
            splitter_state=splitter_state,
            output_format=fmt,
            pro_features=pro_features,
            prefs_path=self._get_write_path(),
            dock_state=dock_state,
            dock_widgets_state=dock_widgets_state,
        )
        self.main_window._save_prompt_options()

    def _get_write_path(self):
        if self.write_legacy_prefs and self.prefs_path:
            return self.prefs_path
        return _prefs_path()

    def load_from_prefs_button_clicked(self):
        prefs_path, _ = _existing_prefs_path()
        if os.path.exists(prefs_path):
            self.load_prefs_if_exists()
            self.main_window.tree_widget.blockSignals(True)
            try:
                iterator = QtWidgets.QTreeWidgetItemIterator(
                    self.main_window.tree_widget)
                while iterator.value():
                    item = iterator.value()
                    if item.flags() & QtCore.Qt.ItemIsUserCheckable and os.path.isfile(item.data(0, QtCore.Qt.UserRole)):
                        item.setCheckState(0, QtCore.Qt.Unchecked)
                    iterator += 1

                for rel_path in self.checked_files_from_prefs:
                    if rel_path in self.main_window.path_to_item:
                        item = self.main_window.path_to_item[rel_path]
                        if os.path.isfile(item.data(0, QtCore.Qt.UserRole)):
                            item.setCheckState(0, QtCore.Qt.Checked)
                            parent = item.parent()
                            while parent:
                                if parent.checkState(0) != QtCore.Qt.PartiallyChecked and parent.checkState(0) != QtCore.Qt.Checked:
                                    parent.setCheckState(
                                        0, QtCore.Qt.PartiallyChecked)
                                parent = parent.parent()
            finally:
                self.main_window.tree_widget.blockSignals(False)
            self.main_window._expand_folders_for_paths(
                self.checked_files_from_prefs)
            self.main_window.text_label.setText(
                "Loaded selection from project preferences")
            self.main_window.update_token_counter()
            if hasattr(self.main_window, "_send_metric_event"):
                self.main_window._send_metric_event(
                    "project_selection_loaded",
                    details={
                        "feature": "saved_project_selection",
                        "selected_file_count": len(self.checked_files_from_prefs),
                    },
                )
        else:
            self.main_window.text_label.setText(
                "No project preferences file found")
